final-step-of-project
dendi135/ssFirstTask pull request #9
Opened 2019-06-18 13:52 UTC by dendi135

Project was comoplited and ready for review

2019-06-18 14:08 UTC, vparlah commented on Task/src/test/java/com/softserve/firsttask/data/City.java
> +    //
Why we need this?

2019-06-18 14:16 UTC, dendi135 commented on Task/src/test/java/com/softserve/firsttask/data/City.java
> +    //
It was fixed already

2019-06-18 15:07 UTC, ghost requested changes
The main data provider logic needs to be reworked. All data from .xls need to be pulled somehow automatically... In case we have 100000 values in file...

Also, I'm unable to run the tests. Please update instructions how to run them

`Volodymyrs-MacBook-Pro:Task volodymyrparlah$ mvn test
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.14
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 14
[INFO] os.detected.classifier: osx-x86_64
[INFO] 
[INFO] -----------------< com.softserve.firsttask:FirstTask >------------------
[INFO] Building FirstTask 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ FirstTask ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/volodymyrparlah/Documents/Learning/ssFirstTask/Task/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ FirstTask ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ FirstTask ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ FirstTask ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- webdriverextensions-maven-plugin:3.1.3:install-drivers (pre-test) @ FirstTask ---
[INFO] Installation directory "/Users/volodymyrparlah/Documents/Learning/ssFirstTask/Task/target/test-classes"
[INFO] Installing drivers from configuration
[INFO] chromedriver-osx-32bit version 75.0.3770.90
[INFO]   Already installed
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ FirstTask ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 22137
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 13.548 s <<< FAILURE! - in TestSuite
[ERROR] beforeClass(com.softserve.firsttask.tests.ValuesTest)  Time elapsed: 2.856 s  <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException: 
session not created: This version of ChromeDriver only supports Chrome version 75
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Volodymyrs-MacBook-Pro.local', ip: 'fe80:0:0:0:142b:cba8:9912:2916%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: 0   chromedriver-osx-32bit              0x000000010fe74319 chromedriver-osx-32bit + 3597081
1   chromedriver-osx-32bit              0x000000010fe03f73 chromedriver-osx-32bit + 3137395
2   chromedriver-osx-32bit              0x000000010fbafc7f chromedriver-osx-32bit + 695423
3   chromedriver-osx-32bit              0x000000010fb1da6b chromedriver-osx-32bit + 96875
4   chromedriver-osx-32bit              0x000000010fb19b18 chromedriver-osx-32bit + 80664
5   chromedriver-osx-32bit              0x000000010fb46139 chromedriver-osx-32bit + 262457
6   chromedriver-osx-32bit              0x000000010fb43753 chromedriver-osx-32bit + 251731
7   chromedriver-osx-32bit              0x000000010fb1faea chromedriver-osx-32bit + 105194
8   chromedriver-osx-32bit              0x000000010fb20b45 chromedriver-osx-32bit + 109381
9   chromedriver-osx-32bit              0x000000010fe32f85 chromedriver-osx-32bit + 3329925
10  chromedriver-osx-32bit              0x000000010fe3e890 chromedriver-osx-32bit + 3377296
11  chromedriver-osx-32bit              0x000000010fe3e628 chromedriver-osx-32bit + 3376680
12  chromedriver-osx-32bit              0x000000010fe12769 chromedriver-osx-32bit + 3196777
13  chromedriver-osx-32bit              0x000000010fe3f108 chromedriver-osx-32bit + 3379464
14  chromedriver-osx-32bit              0x000000010fe26957 chromedriver-osx-32bit + 3279191
15  chromedriver-osx-32bit              0x000000010fe5ba94 chromedriver-osx-32bit + 3496596
16  chromedriver-osx-32bit              0x000000010fe7a047 chromedriver-osx-32bit + 3620935
17  libsystem_pthread.dylib             0x00007fff5b4152eb _pthread_body + 126
18  libsystem_pthread.dylib             0x00007fff5b418249 _pthread_start + 66
19  libsystem_pthread.dylib             0x00007fff5b41440d thread_start + 13


[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ValuesTest>TestRunner.beforeClass:25 » SessionNotCreated session not created: ...
[INFO] 
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.580 s
[INFO] Finished at: 2019-06-18T18:02:38+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project FirstTask: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/volodymyrparlah/Documents/Learning/ssFirstTask/Task/target/surefire-reports/test-output for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/data/PlacesRepository.java
> +   public static City getKyiv() {
We are not using getKyiv, getLviv, getIvanoFrankivsk, so may be deleted.

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/pages/HeaderPart.java
> +    public void clicklatestPlaces() {
```suggestion
    public void clickLatestPlaces() {
```

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/tests/SmokeTest.java
> +        System.out.printf(PlacesRepository.fromExcel("places.xlsx").get(2).getName());
What we are checking here?

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/tools/ExternalReader.java
> +
remove whitespace

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/tools/ListUtils.java
> +
remove whitespace

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/pages/HomePage.java
> +    public GrayBoxComponent getGrayBoxComponent() {
Maybe we can give it a more meaningful name?
smth like: GrayBoxComponent - > SearchPlaceComponent

2019-06-18 15:07 UTC, ghost commented on Task/src/test/java/com/softserve/firsttask/pages/HeaderPart.java
> +    public HomePage gotoHomePage() {
```suggestion
    public HomePage goToHomePage() {
```

2019-06-19 10:06 UTC, ghost approved these changes

2019-06-19 10:07 UTC, merged